-- Create recruits table for tracking recruitment activities
CREATE TABLE IF NOT EXISTS recruits (
  id INT AUTO_INCREMENT PRIMARY KEY,
  recruiting_agent VARCHAR(50),
  recruit_first VARCHAR(100),
  recruit_last VARCHAR(100),
  recruit_middle VARCHAR(100),
  recruit_suffix VARCHAR(20),
  step VARCHAR(50) DEFAULT 'Careers Form',
  email VARCHAR(255),
  phone VARCHAR(20),
  overview_time DATETIME,
  hire VARCHAR(10),
  final_time DATETIME,
  callback_time DATETIME,
  resident_state VARCHAR(5),
  enrolled VARCHAR(5),
  course VARCHAR(255),
  expected_complete_date DATE,
  current_progress VARCHAR(255),
  last_log_prelic DATE,
  prelic_passed VARCHAR(5),
  prelic_cert VARCHAR(255),
  test_date DATE,
  test_passed VARCHAR(5),
  test_cert VARCHAR(255),
  bg_date DATE,
  compliance1 VARCHAR(5),
  compliance2 VARCHAR(5),
  compliance3 VARCHAR(5),
  compliance4 VARCHAR(5),
  compliance5 VARCHAR(5),
  aob VARCHAR(5),
  resident_license_number VARCHAR(50),
  npn VARCHAR(50),
  agentnum VARCHAR(50),
  impact_setup VARCHAR(5),
  training_start_date DATE,
  coded VARCHAR(5),
  code_to VARCHAR(50),
  eapp_username VARCHAR(100),
  impact_username VARCHAR(100),
  referral_source VARCHAR(255),
  aspects TEXT,
  concern TEXT,
  spouse TEXT,
  career_goals TEXT,
  compensation TEXT,
  why_choose TEXT,
  date_added DATETIME DEFAULT CURRENT_TIMESTAMP,
  date_last_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_recruiting_agent (recruiting_agent),
  INDEX idx_step (step),
  INDEX idx_date_added (date_added)
); 