CREATE TABLE IF NOT EXISTS verify (
    id INT PRIMARY KEY AUTO_INCREMENT,
    application_id VARCHAR(255),
    total_annual_premium DECIMAL(10,2),
    total_trial_premium DECIMAL(10,2),
    url VARCHAR(255),
    bank VARCHAR(255),
    agent_ip VARCHAR(45),
    status VARCHAR(50),
    resend_count INT DEFAULT 0,
    resent_time DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    userId INT,
    client_name VARCHAR(255),
    client_phoneNumber VARCHAR(20),
    client_email VARCHAR(255),
    agent_name VARCHAR(255),
    agent_email VARCHAR(255),
    primary_info VARCHAR(255),
    spouse_info VARCHAR(255),
    child1_info VARCHAR(255),
    child2_info VARCHAR(255),
    child3_info VARCHAR(255),
    child4_info VARCHAR(255),
    child5_info VARCHAR(255),
    child6_info VARCHAR(255),
    child7_info VARCHAR(255),
    child8_info VARCHAR(255),
    child9_info VARCHAR(255),
    dui_answer VARCHAR(50),
    arrested_answer VARCHAR(50),
    heart_issues_answer VARCHAR(50),
    high_blood_pressure_answer VARCHAR(50),
    diabetes_answer VARCHAR(50),
    anxiety_depression_answer VARCHAR(50),
    cancer_answer VARCHAR(50),
    medications_answer VARCHAR(50),
    er_visit_answer VARCHAR(50),
    chronic_illness_answer VARCHAR(50),
    senior_rejected_answer VARCHAR(50),
    heart_lung_answer VARCHAR(50),
    cirrhosis_answer VARCHAR(50),
    amputation_answer VARCHAR(50),
    cancer_senior_answer VARCHAR(50),
    oxygen_answer VARCHAR(50),
    archive CHAR(1) DEFAULT 'n',
    agency VARCHAR(255),
    INDEX idx_application_id (application_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_userId (userId)
); 