CREATE TABLE IF NOT EXISTS verify_client (
    id INT PRIMARY KEY AUTO_INCREMENT,
    application_id VARCHAR(255) UNIQUE NOT NULL,
    high_blood_pressure VARCHAR(255) DEFAULT 'n',
    diabetes VARCHAR(255) DEFAULT 'n',
    anxiety_depression VARCHAR(255) DEFAULT 'n',
    medications VARCHAR(255) DEFAULT 'n',
    er_visit VARCHAR(255) DEFAULT 'n',
    arrested VARCHAR(255) DEFAULT 'n',
    dui VARCHAR(255) DEFAULT 'n',
    cancer VARCHAR(255) DEFAULT 'n',
    heart_issues VARCHAR(255) DEFAULT 'n',
    chronic_illness VARCHAR(255) DEFAULT 'n',
    senior_rejected VARCHAR(255) DEFAULT 'n',
    heart_lung VARCHAR(255) DEFAULT 'n',
    cirrhosis VARCHAR(255) DEFAULT 'n',
    amputation VARCHAR(255) DEFAULT 'n',
    cancer_senior VARCHAR(255) DEFAULT 'n',
    oxygen VARCHAR(255) DEFAULT 'n',
    account_verification VARCHAR(255) DEFAULT 'n',
    application_verification VARCHAR(255) DEFAULT 'n',
    agent_contact_request VARCHAR(255) DEFAULT 'No',
    submission_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    client_ip VARCHAR(45),
    INDEX idx_application_id (application_id),
    INDEX idx_submission_date (submission_date)
); 